"""initial_tables

Revision ID: 00b302a762c4
Revises: 
Create Date: 2025-10-23 08:43:59.126202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00b302a762c4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signalements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_signalement', sa.Date(), nullable=False),
    sa.Column('heure_signalement', sa.Time(), nullable=False),
    sa.Column('nom_agent', sa.String(length=100), nullable=False),
    sa.Column('id_agent', sa.String(length=50), nullable=False),
    sa.Column('type_evenement', sa.Enum('REUNION_QUARTIER', 'PUBLICATION_RESEAUX', 'RASSEMBLEMENT_PUBLIC', 'AUTRE', name='typeevenement'), nullable=False),
    sa.Column('gravite', sa.Enum('FAIBLE', 'MOYENNE', 'ELEVEE', name='graviteevenement'), nullable=False),
    sa.Column('lieu', sa.String(length=200), nullable=False),
    sa.Column('source_information', sa.Enum('OBSERVATION_DIRECTE', 'INFORMATEUR', 'RESEAUX_SOCIAUX', 'AUTRE', name='sourceinformation'), nullable=False),
    sa.Column('source_autre', sa.String(length=200), nullable=True),
    sa.Column('action_entreprise', sa.Enum('OBSERVATION', 'ALERTE_TRANSMISE', 'INTERVENTION', 'AUTRE', name='actionentreprise'), nullable=False),
    sa.Column('action_autre', sa.String(length=200), nullable=True),
    sa.Column('commentaire_complementaire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signalements_id'), 'signalements', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_signalements_id'), table_name='signalements')
    op.drop_table('signalements')
    # ### end Alembic commands ###
